spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: xBc3M3av$lv$^QML
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://laien.test:6379"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 10
          connectionMinimumIdleSize: 5
          connectionPoolSize: 10
          database: 0
          dnsMonitoringInterval: 5000
        threads: 8
        nettyThreads: 8
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        "transportMode": "NIO"