server:
  port: 8200
  servlet:
    context-path: /template21Test/
spring:
  application:
    name: template21-test
  main:
    allow-bean-definition-overriding: true
  threads:
    virtual:
      # 开启虚拟线程
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://laien.test:3306/template-cms-java?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: K&e4$PJ9w$23aXYD
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 20
      # 空闲连接存活最大时间，默认5分钟
      idle-timeout: 480000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 30
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 540000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 8000
      # 连接测试query
      connection-test-query: SELECT 1 FROM DUAL
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: xBc3M3av$lv$^QML
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://laien.test:6379"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 10
          connectionMinimumIdleSize: 5
          connectionPoolSize: 10
          database: 0
          dnsMonitoringInterval: 5000
        threads: 8
        nettyThreads: 8
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        "transportMode": "NIO"
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    #    enableOpenAPI3: true
    language: zh-CN
    enable-swagger-models: true
    swagger-model-name: 实体类列表
    enable-document-manage: true
    enable-version: true
    #    enable-author: true
    enable-footer: true
    #    enable-footer-custom-content: true
    footer-custom-content: Apache License 2.0 | Copyright © 2023-present
#    enable-home-custom-content: true
mybatis-flex:
  global-config:
    print-banner: false
#    print-sql: true
#    print-sql-result: false
#logging:
#  level:
#    org.springframework.retry: DEBUG